version: '3'
services:
    blog-backend:
        #image: tsurol/blog:23.06.02.1800_1854a31
        image: tsurol/blog:23.06.06.1023_62e5c14 
        volumes:
            - ./src:/Users/a1/Project/blog-backend/src
        environment:
            - TZ=Asia/Shanghai
            - LANG=C.UTF-8
            - LOCAL_ENV=test
            - PYTHONPATH=./src
        ports:
            - 5856:5856
        command: bash -c "supervisord -c deploy/supervisord.conf -n"